[package]
name = "euler"
version = "0.1.0"
authors = ["Techcable <Techcable@techcable.net>"]
# This isn't a library
publish = false

[dependencies]
clap = "^2.29"
failure = "^0.1.1"
failure_derive = "^0.1.1"
fixedbitset = "^0.1.8"
ndarray = "^0.11.1"
itertools = "^0.7.6"
